## Create instance
- name: Create instance
  openstack.cloud.server:
    state: "{{ state }}"
    name: "{{ item }}"
    image: "{{ os_image }}"
    flavor: "{{ flavor }}"
    key_name: "{{ key_name }}"
    network: "{{ network }}"
    security_groups: "{{ instance_name }}"
    meta:
      hostname: "{{ instance_name }}"
      group: "{{ instance_name }}"
  retries: 3
  async: 300
  poll: 0
  register: servers
  with_sequence: start=1 end={{ number_instances }} format={{ instance_name }}-%d

- name: Checking instance started
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: srv
  until: srv.finished
  retries: 60
  delay: 5
  with_items:
    - "{{ servers.results }}"

## Assign Floating IP
- name: Acquiring Floating IP
  openstack.cloud.floating_ip:
    state: "{{ state }}"
    server: "{{ item.item }}"
    network: "public"
    reuse: true
    # network: "{{ floating_ip_pool }}"
    wait: true
    timeout: 60
  delay: 1
  retries: 3
  async: 60
  poll: 0
  register: server_ip
  with_items:
    - "{{ servers.results }}"

- name: Waiting for IP and Check
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: srv_ip
  until: srv_ip.finished
  retries: 60
  delay: 1
  with_items:
    - "{{ servers.results }}"
