- name: Create security group
  openstack.cloud.security_group:
    state: present
    name: "{{ instance_name }}"
    description: "Security group for {{ instance_name }}"

- name: Add port 22 opening to ips {{ internal_ips }} to rule {{ instance_name }}
  openstack.cloud.security_group_rule:
    security_group: "{{ instance_name }}"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: "{{ item }}"
  with_items:
    - "{{ internal_ips }}"

- name: Add port 80 opening to rule {{ instance_name }}
  openstack.cloud.security_group_rule:
    security_group: "{{ instance_name }}"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
